name: Run JMeter Test Nightly

on:
  workflow_dispatch:     # מאפשר הרצה ידנית דרך כפתור
  schedule:
    - cron: '0 22 * * *'  # רץ כל לילה ב־01:00 שעון ישראל (22:00 UTC)

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk wget
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter test
        run: |
          apache-jmeter-5.6.3/bin/jmeter -n -t JMETER1.jmx -l result.jtl
